// Native Fetch (Node 18+)
async function testo() {
    console.log("Testing /preview...");
    try {
        const response = await fetch('http://localhost:3500/api/rgs/preview', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                config: {
                    gameId: 'test-preview-1',
                    scratch: {
                        layout: { rows: 3, columns: 3 },
                        prizes: [
                            { id: 'WIN', value: 100, payout: 100, isWin: true, weight: 1000 }, // Only wins
                            { id: 'LOSE', value: 0, payout: 0, isWin: false, weight: 0 }
                        ],
                        features: { multipliers: { enabled: true, values: [2, 5] } }
                    }
                }
            })
        });

        const data = await response.json();
        console.log("Status:", response.status);
        if (data.success) {
            console.log("SUCCESS! Grid Generated by Server:");
            console.log("Outcome:", data.outcome.revealMap);
            console.log("Is Win?", data.outcome.isWin);
            console.log("Multiplier:", data.outcome.multiplier);
        } else {
            console.error("FAIL:", data);
        }
    } catch (e) {
        console.error("Error:", e);
    }
}

testo();
